**Paso 1: Preparación del entorno y carga de datos**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
url_viajes = "yellow_tripdata_2024-01.parquet"
url_zonas = "taxi_zone_lookup.csv"

columnas_a_cargar = [
    "tpep_pickup_datetime", 
    "PULocationID", 
    "trip_distance", 
    "fare_amount",
    "tip_amount"
]
viajes = pd.read_parquet(url_viajes, columns=columnas_a_cargar)
zonas = pd.read_csv(url_zonas)

**Paso 2: Evaluar lo cargado**

In [6]:
viajes.head()

  tpep_pickup_datetime  PULocationID  trip_distance  fare_amount  tip_amount
0  2024-01-01 00:57:55           186           1.72         17.7        0.00
1  2024-01-01 00:03:00           140           1.80         10.0        3.75
2  2024-01-01 00:17:06           236           4.70         23.3        3.00
3  2024-01-01 00:36:38            79           1.40         10.0        2.00
4  2024-01-01 00:46:51           211           0.80          7.9        3.20

In [13]:
fecha_max = viajes["tpep_pickup_datetime"].max()
fecha_min = viajes["tpep_pickup_datetime"].min()

print(f"La fecha mínima:{fecha_min}, y la fecha máxima:{fecha_max}")

La fecha mínima:2002-12-31 22:59:39, y la fecha máxima:2024-02-01 00:01:15

In [9]:
viajes.dtypes

tpep_pickup_datetime    datetime64[us]
PULocationID                     int32
trip_distance                  float64
fare_amount                    float64
tip_amount                     float64
dtype: object

In [10]:
viajes.shape

(2964624, 5)

In [11]:
zonas.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

**Paso 3: Filtrar a Enero de 2024**